### ISSUE TITLE
Add way to get the generated team set from simulation

### ISSUE THREAD

**Issue by justino599** [Teamable-Analytics/algorithms#111]
### Issue
- After a simulation is run, it is not possible to recover the team set that was generated from the run

### Suggested Solution
- Save the generated team set to the simulation object and add a getter for retrieving the team set

**Comment by Opeyem1a** [comment]
I have thoughts, @justino599 @Hedgemon4 
Lmk if a meeting time works, think we can go super hard on this

**Comment by Opeyem1a** [comment]
Related #125
