### ISSUE TITLE
Implement friends/enemy satisfaction metric

### ISSUE THREAD

**Issue by justino599** [Teamable-Analytics/algorithms#124]
### Issue
- The friends/enemy staisfaction metric from Keyvan's paper, section 5.1, needs to be implemented
- The detailed description of this metric can be found in the paper, but here is the quick version
    - A student is strictly happy if everyone they wanted on their team *is* on their team
        - How many/percent of students are strictly happy?
    - A team is strictly happy if every member in the team is strictly happy
        - How many/percent of teams are strictly happy?
    - Can also do the above where we measure "happy people" instead of "strictly happy people" where the requirement is relaxed so that only one friend needs be on the team to be satisfied
    - Now, all the above can be done, except measuring satisfaction based on enemies instead of friends

**Comment by Opeyem1a** [comment]
I know you mentioned this is done because I copied over the utils from Keyvan's work, but I don't think we have actual Metric classes for this yet - wanted to see what your plan was for this ticket

**Comment by justino599** [comment]
There is a `Metric` for all of these. In `benchmarking/evaluations/metrics/average_social_satisfied.py` there is a `AverageSocialSatisfaction` class that can take any team metric function from `benchmarking/evaluations/metrics/utils/team_calculations.py`. This seems to suit the needs of measuring social satisfaction already if I'm not mistaken

**Comment by justino599** [comment]
Closing as this was already done and doesn't need to be an open issue anymore
