### ISSUE TITLE
Improve graphing tool

### ISSUE THREAD

**Issue by justino599** [Teamable-Analytics/algorithms#131]
### Issues
- Every line should be distinguishable by 3 characteristics: colour, style (solid line, dashed line, etc.), marker (*, o, x, ...)
- y-axis should be the same (e.g. 0 to 1, or 0 to 100%) 
- Add minor ticks to x-axis - allow user to customize xticks and y-axis if necessary

**Comment by Opeyem1a** [comment]
Does the y-axis need to be the same though? I don't fully get that take

**Comment by justino599** [comment]
To keep this issue up-to-date with private discussions, Opey and I discussed the y-axis problem and came to the following conclusions:
- The programmer should still ultimately have the control of what the y-axis range should be (e.g. a range of 0 to 1 should not be enforced for gini index)
	- A motivating example for why we thought this: "let's say for some cool new metric *in only 1 scenario*, all the values for all algorithms are super low (1-2) but the theoretical max of that metric is high (100), maybe we want that run specifically to graph them from 1-3 just so we can see more closely"
- There should still be a suggested range that will be used most of the time
	- Add to the `TeamSetMetric` interface a "theoretical min/max" value for the metric that can be used by the programmer as the y-axis limits
