### ISSUE TITLE
Rename CONVENTION.md to CONTRIBUTION.md

### ISSUE THREAD

**Issue by Opeyem1a** [Teamable-Analytics/algorithms#93]
I think CONTRIBUTION is the best practice on github for what that file is, in practice - validate this assertion before doing pls

**Comment by EliasPinno** [comment]
I'm unclear if this is correct. If you want the file to behave like a `CONTRIBUTION.md` you definitely need to fill it with more content: the file now kind of just exists as an outline of a few guidelines for random files runtime help but it is not really precisely a guide on how to contribute to the repository. A good example of what a `CONTRIBUTION.md` file should look like is [this](https://contributing.md/example/) with a concrete example being [here](https://github.com/json-e/json-e/blob/main/CONTRIBUTING.md).

**Comment by Opeyem1a** [comment]
Fair @EliasPinno , we can call this closed then
